apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: gateway-service
  description: Gateway Service
  labels:
    goVersion: go1.15.3
    category: music
  tags:
    - go
spec:
  type: service
  lifecycle: production
  owner: infrastructure
  system: gateway
